name: Check that version is updated

on:
  pull_request:
    branches: [ master ]

jobs:
  CheckVersion:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch repo
        run: git fetch

      - name: Version check
        run: |
          if [ -z $(git diff origin/master HEAD -- setup.py | grep version )]
          then
            echo "You should probably update version number"
            exit 1
          fi
      - name: Push new version
        run: |
          version_name=$(python setup.py --version)
          git tag -a $version_name -m "new version $version_name"
          git push origin $version_name
